Traceback (most recent call last):
  File "C:\Files\Egyetem\Szakdolgozat\RL\Sol\Model\pybullet_drone_simulator.py", line 678, in <module>
    sim.run_full()
  File "C:\Files\Egyetem\Szakdolgozat\RL\Sol\Model\pybullet_drone_simulator.py", line 299, in run_full
    train_env = self.make_env(multi=False, gui=False)
  File "C:\Files\Egyetem\Szakdolgozat\RL\Sol\Model\pybullet_drone_simulator.py", line 130, in make_env
    return _init()
  File "C:\Files\Egyetem\Szakdolgozat\RL\Sol\Model\pybullet_drone_simulator.py", line 103, in _init
    env = PBDroneEnv(
  File "C:\Files\Egyetem\Szakdolgozat\RL\.\Sol\Model\PBDroneEnv.py", line 46, in __init__
    self.eps = np.finfo(np.float32.dtype).eps
  File "C:\Users\xx4qw\anaconda3\envs\CondaDrone\lib\site-packages\numpy\core\getlimits.py", line 492, in __new__
    raise ValueError("data type %r not inexact" % (dtype))
ValueError: data type <class 'numpy.object_'> not inexact